---
- name: " "
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - include_role: {name: function/ansible-test-runner}
      vars:
        _test_case_title: "[pound] group MUST (1) be defined in the ansible inventory and (2) have at least one valid assigned IP"
        _should_debug_test: false
        _bash_test_code: |
          set -x
          # fail if nothing defined in the ansible [pound] inventory group
          numberOfIpsInPoundGroup={{groups['pound'] | length | default(0)}}
          (( ${numberOfIpsInPoundGroup} == 0 )) && echo "{{_test_case_title}}" && exit 1
          
          # otherwise pass
          exit 0

    - include_role: {name: function/ansible-test-runner}
      vars:
        _test_case_title: "[apache] group MUST (1) be defined in the ansible inventory and (2) have at least one valid assigned IP"
        _should_debug_test: false
        _bash_test_code: |
          set -x
          # fail if nothing defined in the ansible [pound] inventory group
          numberOfIpsInPoundGroup={{groups['apache'] | length | default(0)}}
          (( ${numberOfIpsInPoundGroup} == 0 )) && echo "{{_test_case_title}}" && exit 1
          
          # otherwise pass
          exit 0

    - include_role: {name: function/ansible-test-runner}
      vars:
        _test_case_title: Linux kernal should be 4.1.12.x
        _should_debug_test: false
        _bash_test_code: |
          set -x
          actual=$( uname -r )
          expected="4\.1\.12-112\.14\.[0-9]{0,3}\.el6uek\.x86_64$"
          echo "${actual}" | grep -E "${expected}"

    - include_role: {name: function/ansible-test-runner}
      vars:
        _test_case_title: Load Balancer should be able to connect to Apache servers
        _should_debug_test: false
        _bash_test_code: |
          set -x
          {% for host in groups['pound'] %}
          actual=$(curl -sS {{host}})
          expected="hello"
          echo "${actual}" | grep "${expected}"
          {% endfor %}

- name: " "
  hosts: pound
  gather_facts: false
  tasks:
    - include_role: {name: function/ansible-test-runner}
      vars:
        _test_case_title: ensure pound exists
        _should_debug_test: false
        _bash_test_code: |
          rpm -qa | grep Pound
