---
- name: " "
  hosts: pound
  gather_facts: false
  tasks:
    - include_role: {name: function/ansible-test-runner}
      vars:
        _test_case_title: pound load balancer should be installed
        _should_debug_test: false
        _bash_test_code: |
          rpm -qa | grep Pound

- name: " "
  hosts: all
  become: true
  gather_facts: false
  tasks:
    # test that all common inventory groups are defined; only run once on one server
    - include_role: {name: function/verify-whether-groups-are-defined}
      vars:
        _list_of_mandetory_inventory_groups:
          - "pound"
          - "apache"

    - include_role: {name: function/ansible-test-runner}
      vars:
        _test_case_title: all hosts should be at linux kernal 4.1.12.x
        _should_debug_test: false
        _bash_test_code: |
          set -x
          actual=$( uname -r )
          expected="4\.1\.12-112\.14\.[0-9]{0,3}\.el6uek\.x86_64$"
          echo "${actual}" | grep -E "${expected}"

    - include_role: {name: function/ansible-test-runner}
      vars:
        _test_case_title: all servers should be able to use pound load balancer
        _should_debug_test: false
        _bash_test_code: |
          set -x
          {% for host in groups['pound'] %}
          actual=$(curl -sS {{host}})
          expected="hello"
          echo "${actual}" | grep "${expected}"
          {% endfor %}
