---
# Keep this do-nothing task as this is required for vagrant provisioning
# NOTE: proxy then EPEL should be setup before anything else!
- name: site.yml | All roles
  hosts: all
  become: true
  become_user: root
  roles:
    - epel-6.8-repository-installer
    - common-utility-installer

- name: Ensure that the vagrant cleanup happens at the end!
  hosts: all
  become: true
  become_user: root
  roles:
    - vagrant-base-cleaner


